# Generated by Django 3.0.8 on 2020-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('first', models.CharField(blank=True, max_length=255)),
                ('last', models.CharField(blank=True, max_length=255)),
                ('street_number', models.CharField(blank=True, max_length=255)),
                ('street_name', models.IntegerField(blank=True, default=0)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('postcode', models.IntegerField(blank=True, default=0)),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255)),
                ('timezone_offset', models.CharField(blank=True, max_length=255)),
                ('timezone_description', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('login_uuid', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('password_salt', models.CharField(blank=True, max_length=255)),
                ('password_md5', models.CharField(blank=True, max_length=255)),
                ('password_sha1', models.CharField(blank=True, max_length=255)),
                ('password_sha256', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('registered_date', models.DateTimeField(blank=True)),
                ('registered_age', models.IntegerField(blank=True, default=0)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('cell', models.CharField(blank=True, max_length=255)),
                ('id_name', models.CharField(blank=True, max_length=255)),
                ('id_value', models.CharField(blank=True, max_length=255)),
                ('picture_large', models.CharField(blank=True, max_length=255)),
                ('picture_medium', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('nat', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
