# Generated by Django 3.0.8 on 2020-07-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_remove_person_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='registered_date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
