# Generated by Django 3.0.8 on 2020-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20200729_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='first',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
