# Generated by Django 3.0.8 on 2020-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20200729_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='street_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='street_number',
            field=models.IntegerField(),
        ),
    ]
