# Generated by Django 3.0.8 on 2020-07-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_auto_20200729_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='longitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='postcode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
