# Generated by Django 3.0.8 on 2020-07-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0007_auto_20200729_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='days_to_birthday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='cell',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='login_uuid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='nat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='password_md5',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='password_salt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='password_sha1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='password_sha256',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture_large',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture_medium',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='thumbnail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='timezone_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='timezone_offset',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
