# Generated by Django 3.0.8 on 2020-07-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0008_auto_20200730_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture_large',
        ),
        migrations.RemoveField(
            model_name='person',
            name='picture_medium',
        ),
    ]
